package com.friends.alarm.entity

enum class AlarmType {
    FRIEND_REQUEST,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    FRIEND_REQUEST_BLOCKED,

    CHAT_ROOM_INVITATION,
    CHAT_ROOM_INVITATION_ACCEPTED,
    CHAT_ROOM_INVITATION_REJECTED,
}
